server:
  port: 8800
logging.level:
  root: INFO
  org.springframework.web: INFO
  org.hibernate: INFO
db1:
  datasource:
    url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
db2:
  datasource:
    url: jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: