server:
  port: 8800
logging.level:
  root: INFO
  org.springframework.web: INFO
  org.hibernate: INFO
db1:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: anayonkar
    password: anayonkar
db2:
  datasource:
    url: jdbc:mysql://localhost:3306/db2
    username: anayonkar
    password: anayonkar